### ISSUE TITLE
Things to update for version 0.0.1

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jaxDecomp#10]
- [ ] slide_unpad does not seem to be too happy with getting complex numbers as inputs https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/18:
```
  File "/mnt/home/flanusse/repo/jaxDecomp/scripts/demo.py", line 58, in <module>
    recarray = slice_unpad(exchanged_reduced, padding_width, pdims)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: custom_partitioner: TypeError: pad operand and padding_value must be same dtype: got complex64 and float32.
```
- [ ] https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/17
- [ ] Can we remove jaxdecomp.finalize() entirely? 
- [ ] https://github.com/DifferentiableUniverseInitiative/jaxDecomp/issues/11
- [x] https://github.com/DifferentiableUniverseInitiative/jaxDecomp/issues/13
- [ ] Add a mechanism to run all the tests at once (currently, they can only be ran one by one)
- [ ] halo_reduce does not work as intended.

**Comment by ASKabalan** [comment]
About running all tests together (just for future reference).

`pytest` share the session between tests.. So it has to be done using the pytest session scope
Because we cannot call `jax.distributed.initialize() `twice
Other than that, there should not be any issues
