### ISSUE TITLE
Manual assigment of GPU per rank 

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jaxDecomp#13]
I noticed the following potential issue here:
https://github.com/DifferentiableUniverseInitiative/jaxDecomp/blob/95415b118f08900858c10929eee3ce34461399e9/src/grid_descriptor_mgr.cc#L35
This should not be necessary, the gpu we use is going to be decided by the stream we are provided with by jax. It also has the potential of being different between what jax decides and the rank decided here.

This is might also possibly be why the gpu binding is not working on jean zay.

**Comment by ASKabalan** [comment]
I agree that this is not necessary, and perhaps can cause future bugs (I completly forget about it).
`cudaSetDevice` is meant for single controller multi GPU programming in general.
But it is not related to Jean Zay's issue.
Jean Zay issue is reproducible without jaxDecomp .. it is an issue with the GPU binding in multi-process setups.
