### ISSUE TITLE
[Installation error] Run setup.py，command execution error

### ISSUE THREAD

**Issue by hai4john** [DifferentiableUniverseInitiative/jaxDecomp#3]
error message：

CMake Error at CMakeLists.txt:5 (find_package):
By not providing "FindNVHPC.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "NVHPC", but
CMake did not find one.

Could not find a package configuration file provided by "NVHPC" with any of
the following names:

NVHPCConfig.cmake
nvhpc-config.cmake
Add the installation prefix of "NVHPC" to CMAKE_PREFIX_PATH or set
"NVHPC_DIR" to a directory containing one of the above files. If "NVHPC"
provides a separate development package or SDK, be sure it has been
installed.

-- Configuring incomplete, errors occurred!

**Comment by EiffL** [comment]
Hi @hai4john, it looks like CMake is not finding the config file that is packaged with the NVHPC SDK.

You probably need to run this line before doing the pip install:
```python
$ export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$NVCOMPILERS/$NVARCH/22.9/cmake
$ pip install --user .
```
but this asssumes that you have NVHPC installed correctly in your environment, and you may need to update the path if you are using a different version that is not 22.9

Essentially, you need to provide the path to nvhpc-config.cmake, which should hidden somewhere in a `cmake` folder in the NVHPC SDK.

Hope this helps!

**Comment by hai4john** [comment]
Thank you for your reply

**Comment by hai4john** [comment]
Thank you for your reply

**Comment by hai4john** [comment]
Thank you for your reply
ls /opt/nvidia/hpc_sdk/Linux_x86_64/22.11/
comm_libs  compilers  cuda  examples  math_libs  profilers  REDIST

 The NVHPC SDK looks not find the CMake config file under the dir.


 find /opt/nvidia/hpc_sdk/Linux_x86_64/22.11/ -name *config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/comm_libs/hpcx/hpcx-2.12/ucx/mt/lib/cmake/ucx/ucx-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/comm_libs/hpcx/hpcx-2.12/ucx/prof/lib/cmake/ucx/ucx-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/comm_libs/hpcx/hpcx-2.12/ucx/lib/cmake/ucx/ucx-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/comm_libs/hpcx/hpcx-2.12/ucx/debug/lib/cmake/ucx/ucx-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/comm_libs/hpcx/hpcx-2.12/ucc/lib/cmake/ucc/ucc-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/comm_libs/hpcx/hpcx-2.12/ucc/debug/lib/cmake/ucc/ucc-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/cuda/11.8/targets/x86_64-linux/lib/cmake/cub/cub-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/cuda/11.8/targets/x86_64-linux/lib/cmake/thrust/thrust-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/cuda/11.8/targets/x86_64-linux/lib/cmake/libcudacxx/libcudacxx-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/compilers/include-stdpar/cub/cmake/cub-config.cmake
/opt/nvidia/hpc_sdk/Linux_x86_64/22.11/compilers/include-stdpar/thrust/cmake/thrust-config.cmake

can you provide nvhpc-config.cmake sample files

**Comment by hai4john** [comment]
Hi @EiffL , It looks ok after install the NVHPC SDK 22.9. 
Thanks
